version: "3"

services:
  db:
    container_name: db_dev
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=pycontw2016
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secretpostgres
    ports:
      - ${COMPOSE_DB_PORT:-5432}:5432
  pycontw:
    container_name: pycontw_dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./src:/usr/local/app/src
      - ./logs:/usr/local/app/logs
    ports:
      - "${COMPOSE_APP_PORT:-8000}:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:secretpostgres@db:5432/pycontw2016
    command:
      - bash
      - -c
      - |
        until pg_isready -h db; do
          echo 'Waiting for PostgreSQL to be available...'
          sleep 1
        done
        python3 manage.py runserver 0.0.0.0:8000
    working_dir: /usr/local/app/src
